---
apiVersion: v1
offerings:
  - name: terraform-ibm-kms-key-ring
    kind: module
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 0efb177d-37a3-468d-b09a-6b863a293310
    examples:
      - name: basic
        mark_ready: true
      - name: complete
        mark_ready: true
